export const videoFormat = {
  width: 1920,
  height: 1080,
  fps: 30,
  background: '#07101f',
};

export const scenes = [
  {
    id: 'title',
    type: 'title',
    durationMs: 7_000,
    eyebrow: 'Google OAuth verification',
    title: 'Email Agent MCP',
    subtitle: 'Authentic product evidence · gmail.modify',
    narration: 'This video demonstrates the production Email Agent MCP OAuth client and the Gmail features enabled by the requested permission.',
  },
  {
    id: 'identity',
    type: 'capture',
    capture: 'identity',
    requiredKind: 'video',
    minimumCaptureMs: 12_000,
    durationMs: 18_000,
    chapter: '01',
    title: 'Product identity & privacy',
    caption: 'Public homepage → visible privacy-policy link → Google-data section',
    recordingInstruction: 'Record usejunior.com/products/email-agent-mcp, click its privacy link, and show the Google-data section.',
    narration: 'Email Agent MCP is an open-source, locally run email client and productivity integration. Its public homepage links directly to the privacy policy and Google-data disclosures.',
  },
  {
    id: 'auth-platform',
    type: 'capture',
    capture: 'auth-platform',
    requiredKind: 'video',
    minimumCaptureMs: 15_000,
    durationMs: 22_000,
    chapter: '02',
    title: 'Production client & requested scope',
    caption: 'One Web client · gmail.modify · Email client · Email productivity',
    recordingInstruction: 'Record Google Auth Platform Clients and Data Access. Show only the production Web client and its non-secret client ID; show gmail.modify and the Email client + Email productivity selections. Never reveal the client secret.',
    narration: 'The production project contains the hosted Web OAuth client. Data Access requests gmail.modify and identifies the product as an email client and email productivity application.',
  },
  {
    id: 'architecture-intro',
    type: 'architecture',
    durationMs: 11_000,
    title: 'OAuth broker, direct Gmail data path',
    narration: 'The hosted broker exchanges authorization codes and refreshes tokens. Gmail messages travel directly between the user’s local process and Google; the broker never receives email content.',
  },
  {
    id: 'configure',
    type: 'capture',
    capture: 'configure',
    requiredKind: 'video',
    minimumCaptureMs: 10_000,
    durationMs: 16_000,
    chapter: '03',
    title: 'Configure the distributed CLI',
    caption: 'email-agent-mcp configure --provider gmail',
    recordingInstruction: 'Using a clean local profile, record the released CLI version and the configure command through the browser handoff. Do not display environment variables.',
    narration: 'This is the same public CLI users install. Configuration starts the hosted broker authorization flow at oauth.usejunior.com.',
  },
  {
    id: 'oauth-consent',
    type: 'capture',
    capture: 'oauth-consent',
    requiredKind: 'video',
    minimumCaptureMs: 45_000,
    durationMs: 65_000,
    chapter: '04',
    title: 'Complete, authentic OAuth grant',
    caption: 'English consent screen · exact app identity · full permission visible',
    recordingInstruction: 'Continuously record the broker redirect, account chooser, any warning, app branding, expanded permission “Read, compose, and send emails from your Gmail account”, Allow/Continue, broker completion, and return to terminal.',
    narration: 'The user sees the complete Google consent flow in English, including the exact application identity and permission to read, compose, and send Gmail messages. The user explicitly continues before any Gmail access occurs.',
  },
  {
    id: 'connected',
    type: 'capture',
    capture: 'connected',
    requiredKind: 'video',
    minimumCaptureMs: 6_000,
    durationMs: 10_000,
    chapter: '05',
    title: 'Connected test mailbox',
    caption: 'Dedicated synthetic mailbox · no personal content',
    recordingInstruction: 'Record the terminal connection success and email-agent-mcp status for the dedicated review mailbox. Never open the token file.',
    narration: 'Authorization returns to the local CLI, which reports the dedicated synthetic review mailbox as connected.',
  },
  {
    id: 'read',
    type: 'capture',
    capture: 'read',
    requiredKind: 'video',
    minimumCaptureMs: 30_000,
    durationMs: 48_000,
    chapter: '06',
    title: 'Search, read & retrieve the thread',
    caption: 'list_emails → search_emails → read_email → get_thread',
    recordingInstruction: 'Record list_emails, search_emails, read_email, and get_thread against the seeded EA-MCP REVIEW READ 001 synthetic message.',
    narration: 'List and search return Gmail message metadata. Read retrieves the selected synthetic message, and get thread returns its conversation. Gmail API traffic is direct from this local process.',
  },
  {
    id: 'send-reply',
    type: 'capture',
    capture: 'send-reply',
    requiredKind: 'video',
    minimumCaptureMs: 40_000,
    durationMs: 65_000,
    chapter: '07',
    title: 'Compose, send & reply',
    caption: 'Local allowlist · synthetic self-send · threaded reply · Gmail confirmation',
    recordingInstruction: 'Record send_email to the same allowlisted test account, confirm it in Gmail, run reply_to_email, then show the resulting Gmail thread. Do not demo drafts until their Gmail ID path passes a live smoke.',
    narration: 'Email Agent MCP composes and sends a synthetic message through the Gmail API, restricted by the local recipient allowlist. It then sends a threaded reply and confirms the conversation in Gmail.',
  },
  {
    id: 'architecture-summary',
    type: 'architecture',
    durationMs: 12_000,
    title: 'Content stays out of the broker',
    summary: true,
    narration: 'Only authorization codes and OAuth tokens traverse the broker for exchange and refresh. Message bodies stay between the local application and Gmail.',
  },
  {
    id: 'revoke',
    type: 'capture',
    capture: 'revoke',
    requiredKind: 'video',
    minimumCaptureMs: 12_000,
    durationMs: 22_000,
    chapter: '08',
    title: 'User control & revocation',
    caption: 'Remove local credentials · revoke Google Account access',
    recordingInstruction: 'Record the documented local credential-removal guidance and the Google Account third-party access page for revocation. Do not reveal token-file contents.',
    narration: 'The user can remove local credentials and revoke the application’s access from their Google Account at any time.',
  },
  {
    id: 'closing',
    type: 'closing',
    durationMs: 8_000,
    eyebrow: 'Review summary',
    title: 'One explicit grant. User-directed Gmail actions.',
    points: [
      'No advertising or sale of Gmail data',
      'No generalized AI-model training',
      'No email content stored by the OAuth broker',
    ],
    narration: 'UseJunior does not sell Gmail data, use it for advertising, or use it to train generalized AI models. Thank you for reviewing Email Agent MCP.',
  },
];
